[package]
name = "mcw_rs"
version = "0.1.0"
authors = ["Javagedes <joey.vagedes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3.2", features = ["io-util", "process"] }
